joy_node:
  deadzone: 0.01
  autorepeat_rate: 20
  coalesce_interval: 0.01
  dev: /dev/input/js0

teleop:
  ackermann:
    type: topic
    message_type: ackermann_msgs/AckermannDrive
    topic_name: ackermann_cmd
    deadman_buttons: [4]
    axis_mappings:
      -
        axis: 1
        target: speed
        scale: 1.35                   # joystick will command plus or minus 2 meters / second
        offset: 0.0
      -
        axis: 3
        target: steering_angle
        scale: 0.34                  # joystick will command plus or minus ~20 degrees steering angle
        offset: 0.0
